version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5433:5433"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456789"
    command: -p 5433